# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

State.create(name: 'Alabama', symbol: 'AL', elite_ship_time_min: '1', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Alaska', symbol: 'AK', elite_ship_time_min: '3', elite_ship_time_max: '3', pacu_ship_time_min: '3', pacu_ship_time_max: '3', donatable: 'FALSE')
State.create(name: 'Arizona', symbol: 'AZ', elite_ship_time_min: '4', elite_ship_time_max: '5', pacu_ship_time_min: '1', pacu_ship_time_max: '2', donatable: 'TRUE')
State.create(name: 'Arkansas', symbol: 'AR', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'California', symbol: 'CA', elite_ship_time_min: '4', elite_ship_time_max: '5', pacu_ship_time_min: '1', pacu_ship_time_max: '2', donatable: 'TRUE')
State.create(name: 'Colorado', symbol: 'CO', elite_ship_time_min: '3', elite_ship_time_max: '3', pacu_ship_time_min: '3', pacu_ship_time_max: '3', donatable: 'TRUE')
State.create(name: 'Connecticut', symbol: 'CT', elite_ship_time_min: '3', elite_ship_time_max: '3', pacu_ship_time_min: '5', pacu_ship_time_max: '5', donatable: 'TRUE')
State.create(name: 'Delaware', symbol: 'DE', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Florida', symbol: 'FL', elite_ship_time_min: '1', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Georgia', symbol: 'GA', elite_ship_time_min: '1', elite_ship_time_max: '1', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Hawaii', symbol: 'HI', elite_ship_time_min: '5', elite_ship_time_max: '5', pacu_ship_time_min: '3', pacu_ship_time_max: '3', donatable: 'FALSE')
State.create(name: 'Idaho', symbol: 'ID', elite_ship_time_min: '5', elite_ship_time_max: '6', pacu_ship_time_min: '2', pacu_ship_time_max: '3', donatable: 'FALSE')
State.create(name: 'Illinois', symbol: 'IL', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Indiana', symbol: 'IN', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Iowa', symbol: 'IA', elite_ship_time_min: '2', elite_ship_time_max: '3', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Kansas', symbol: 'KS', elite_ship_time_min: '2', elite_ship_time_max: '3', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Kentucky', symbol: 'KY', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Louisiana', symbol: 'LA', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Maine', symbol: 'ME', elite_ship_time_min: '3', elite_ship_time_max: '4', pacu_ship_time_min: '5', pacu_ship_time_max: '5', donatable: 'FALSE')
State.create(name: 'Maryland', symbol: 'MD', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'FALSE')
State.create(name: 'Massachusetts', symbol: 'MA', elite_ship_time_min: '3', elite_ship_time_max: '3', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'TRUE')
State.create(name: 'Michigan', symbol: 'MI', elite_ship_time_min: '2', elite_ship_time_max: '3', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'FALSE', notes: 'Can donate in Detroit')
State.create(name: 'Minnesota', symbol: 'MN', elite_ship_time_min: '3', elite_ship_time_max: '4', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'FALSE')
State.create(name: 'Mississippi', symbol: 'MS', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Missouri', symbol: 'MO', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Montana', symbol: 'MT', elite_ship_time_min: '5', elite_ship_time_max: '5', pacu_ship_time_min: '3', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Nebraska', symbol: 'NE', elite_ship_time_min: '3', elite_ship_time_max: '4', pacu_ship_time_min: '3', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Nevada', symbol: 'NV', elite_ship_time_min: '5', elite_ship_time_max: '6', pacu_ship_time_min: '1', pacu_ship_time_max: '3', donatable: 'TRUE')
State.create(name: 'New Hampshire', symbol: 'NH', elite_ship_time_min: '3', elite_ship_time_max: '3', pacu_ship_time_min: '5', pacu_ship_time_max: '5', donatable: 'FALSE')
State.create(name: 'New Jersey', symbol: 'NJ', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'New Mexico', symbol: 'NM', elite_ship_time_min: '4', elite_ship_time_max: '4', pacu_ship_time_min: '3', pacu_ship_time_max: '3', donatable: 'FALSE')
State.create(name: 'New York', symbol: 'NY', elite_ship_time_min: '2', elite_ship_time_max: '3', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'TRUE')
State.create(name: 'North Carolina', symbol: 'NC', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'TRUE')
State.create(name: 'North Dakota', symbol: 'ND', elite_ship_time_min: '3', elite_ship_time_max: '4', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'FALSE')
State.create(name: 'Ohio', symbol: 'OH', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Oklahoma', symbol: 'OK', elite_ship_time_min: '3', elite_ship_time_max: '3', pacu_ship_time_min: '3', pacu_ship_time_max: '3', donatable: 'TRUE')
State.create(name: 'Oregon', symbol: 'OR', elite_ship_time_min: '5', elite_ship_time_max: '6', pacu_ship_time_min: '2', pacu_ship_time_max: '3', donatable: 'FALSE')
State.create(name: 'Pennsylvania', symbol: 'PA', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Rhode Island', symbol: 'RI', elite_ship_time_min: '3', elite_ship_time_max: '3', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'South Carolina', symbol: 'SC', elite_ship_time_min: '1', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'FALSE')
State.create(name: 'South Dakota', symbol: 'SD', elite_ship_time_min: '4', elite_ship_time_max: '5', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'FALSE')
State.create(name: 'Tennessee', symbol: 'TN', elite_ship_time_min: '1', elite_ship_time_max: '2', pacu_ship_time_min: '8', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Texas', symbol: 'TX', elite_ship_time_min: '3', elite_ship_time_max: '4', pacu_ship_time_min: '3', pacu_ship_time_max: '4', donatable: 'FALSE')
State.create(name: 'Utah', symbol: 'UT', elite_ship_time_min: '5', elite_ship_time_max: '5', pacu_ship_time_min: '2', pacu_ship_time_max: '2', donatable: 'TRUE')
State.create(name: 'Vermont', symbol: 'VT', elite_ship_time_min: '3', elite_ship_time_max: '3', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'TRUE')
State.create(name: 'Virginia', symbol: 'VA', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'TRUE')
State.create(name: 'Washington', symbol: 'WA', elite_ship_time_min: '5', elite_ship_time_max: '5', pacu_ship_time_min: '3', pacu_ship_time_max: '3', donatable: 'FALSE')
State.create(name: 'West Virginia', symbol: 'WV', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '5', donatable: 'TRUE')
State.create(name: 'Wisconsin', symbol: 'WI', elite_ship_time_min: '2', elite_ship_time_max: '3', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Wyoming', symbol: 'WY', elite_ship_time_min: '3', elite_ship_time_max: '4', pacu_ship_time_min: '3', pacu_ship_time_max: '3', donatable: 'FALSE')
State.create(name: 'District of Columbia', symbol: 'DC', elite_ship_time_min: '2', elite_ship_time_max: '2', pacu_ship_time_min: '4', pacu_ship_time_max: '4', donatable: 'TRUE')
State.create(name: 'Puerto Rico', symbol: 'PR', elite_ship_time_min: '4', elite_ship_time_max: '4', pacu_ship_time_min: '6', pacu_ship_time_max: '6', donatable: 'TRUE')